apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: search
spec:
  version: 7.10.2
  count: 1
  elasticsearchRef:
    name: search 
---
apiVersion: v1
kind: Secret
metadata:
  name: search-kibana-user
stringData:
  users: |-
    admin:admin
  users_roles: |-
    admin:admin