apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: royalafg-user
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api/user`)
      kind: Rule
      services:
        - name: royalafg-user
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: royalafg-user
spec:
  selector:
    app: royalafg-user
  ports:
    - name: grpc
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-user
data:
  config.yaml: |
    grpc_port: 5001
    http_port: 8080
    mongodb_url: mongodb://admin:admin@localhost:27017
    jwt_signing_key: testsecret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: royalafg-user
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "vault.hashicorp.com/agent-inject": "true"
        "vault.hashicorp.com/agent-inject-secret-mongodb.yaml": "kv-v2/royalafg-user-mongo"
        "vault.hashicorp.com/agent-inject-template-mongodb.yaml": |
          {{- with secret "kv-v2/royalafg-user-mongo" -}}
          mongodb_url: {{.Data.data.url}}
          {{- end }}
        "vault.hashicorp.com/agent-inject-secret-session.yaml": "kv-v2/session-secret"
        "vault.hashicorp.com/agent-inject-template-session.yaml": |
          {{- with secret "kv-v2/session-secret" -}}
          jwt_signing_key: {{.Data.data.secret}}
          {{- end }}
        "vault.hashicorp.com/role": user-role
      labels:
        app: royalafg-user
    spec:
      serviceAccountName: royalafg-user
      containers:
        - name: royalafg-user
          imagePullPolicy: Always
          image: docker.io/johnnys318/royalafg_user:latest
          resources:
            requests:
              memory: 10Mi
              cpu: 50m
            limits:
              cpu: 150m
              memory: 50Mi
          ports:
            - containerPort: 5001
              name: grpc
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: royalafg-user-config
              mountPath: "/etc/royalafg-user" 

      volumes:
        - name:  royalafg-user-config
          configMap:
              name: royalafg-user